version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tuiservice:latest
    container_name: web-vol
    restart: on-failure
    ports:
      - "8081:8080"
    expose:
      - 8080
    environment:
      - API_GITHUB_USERS_ENDPOINT=https://api.github.com/users/
      - API_GITHUB_REPOS_ENDPOINT=https://api.github.com/repos/
      - GITHUB_TOKEN=